# Generated by Django 6.0.6 on 2026-08-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_pomodorosession_is_completed_pomodorosession_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomodorosession',
            old_name='completed_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pomodorosession',
            old_name='duration',
            new_name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='pomodorosession',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='session_type',
            field=models.CharField(choices=[('pomodoro', 'Pomodoro'), ('short', 'Short Break'), ('long', 'Long Break')], default='pomodoro', max_length=20),
        ),
    ]
